# Rockchip RK3566 quad core 2GB-8GB GBE eMMC NVMe USB3 WiFi
BOARD_NAME="BigTreeTech CB2"
BOARD_VENDOR="bigtreetech"
BOARDFAMILY="rockchip64"
BOARD_MAINTAINER="JohnTheCoolingFan"
INTRODUCED="2022"
BOOTCONFIG="bigtreetech_cb2_defconfig"
BOOT_SOC="rk3566"
KERNEL_TARGET="btt,current,edge"
KERNEL_TEST_TARGET="current"
BOOT_FDT_FILE="rockchip/rk3566-bigtreetech-cb2.dtb"
BOOT_SCENARIO="binman"
BOOTFS_TYPE="fat"
BOOT_FS_LABEL="BOOT"
OVERLAY_PREFIX='rk3566'
SERIALCON="tty1"
# KERNEL_BTF="no" # for debug kernel
# GHCR_MIRROR="nju" # for download "linux-complete.git.tar"
VENDOR="BIGTREETECH-CB2"
REVISION="3.1.0-"$(cat "${SRC}"/VERSION)
BTT_HOSTNAME="BIGTREETECH-CB2"
BTT_HDMI_AUDIODEV="hw:0,0"
BTT_KS_SRC_LIST="HDMI-1 DSI-1"

function pre_customize_image__bigtreetech_cb2() {
    # /sys/class/leds/pad7_vibration/brightness for user group
    cp "${SRC}"/packages/bsp/common/etc/udev/rules.d/99-pad7-vibration.rules "${SDCARD}"/etc/udev/rules.d

    # fixed systemd-shutdown[1]: Failed to set watchdog hardware timeout to 10min: Invalid argument
    sed -i 's/^#\?RebootWatchdogSec=.*/RebootWatchdogSec=off/' "${SDCARD}"/etc/systemd/system.conf

    # install camera-engine-rkaiq (rkaiq_3A_server)
    cp "${SRC}"/packages/bsp/rockchip/camera-engine-rkaiq/usr/lib/* "${SDCARD}"/usr/lib/
    cp "${SRC}"/packages/bsp/rockchip/camera-engine-rkaiq/usr/bin/* "${SDCARD}"/usr/bin/

    cp "${SRC}"/packages/bsp/rockchip/camera-engine-rkaiq/etc/init.d/* "${SDCARD}"/etc/init.d/
    mkdir "${SDCARD}"/etc/iqfiles/
    cp "${SRC}"/packages/bsp/rockchip/camera-engine-rkaiq/etc/iqfiles/* "${SDCARD}"/etc/iqfiles/

    cp "${SRC}"/packages/bsp/rockchip/camera-engine-rkaiq/rkaiq_3A.service "${SDCARD}"/lib/systemd/system/
    chroot_sdcard systemctl enable rkaiq_3A

    # /dev/v4l/by-id/ and /dev/v4l/by-path/(virtual usb) for CSI devices (detected in crowsnest)
    cp "${SRC}"/packages/bsp/rockchip/camera-engine-rkaiq/99-csi-v4l-crowsnest.rules "${SDCARD}"/etc/udev/rules.d
    sudo sed -i 's/KERNEL=="video\*|vbi\*", ENV{ID_PATH}=="?\*",[[:space:]]*SYMLINK+="v4l\/by-path\/$env{ID_PATH}-video-index$attr{index}"/KERNEL=="video*|vbi*", ENV{ID_PATH}=="?*", ATTRS{name}!="rkisp*", SYMLINK+="v4l\/by-path\/$env{ID_PATH}-video-index$attr{index}"/' "${SDCARD}"/usr/lib/udev/rules.d/60-persistent-v4l.rules

    # install ffmpeg with h264_rkmpp
    cp "${SRC}"/packages/bsp/rockchip/ffmpeg_h264_rkmpp/usr/lib/* "${SDCARD}"/usr/lib/
    cp "${SRC}"/packages/bsp/rockchip/ffmpeg_h264_rkmpp/usr/bin/ffmpeg "${SDCARD}"/usr/local/bin/

    # /dev/mpp_service for user group
    cp "${SRC}"/packages/bsp/rockchip/ffmpeg_h264_rkmpp/99-mpp-service.rules "${SDCARD}"/etc/udev/rules.d
}
